# Generated by Django 4.2.30 on 2026-07-04 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Main Bar', max_length=120)),
                ('business_date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Till Close'), ('TOAST', 'Toast'), ('LIGHTSPEED', 'Lightspeed'), ('SQUARE', 'Square'), ('CLOVER', 'Clover'), ('OTHER', 'Other')], default='MANUAL', max_length=24)),
                ('sync_mode', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CSV', 'CSV Import'), ('LIVE', 'Live Sync')], default='MANUAL', max_length=16)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tips', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transactions', models.PositiveIntegerField(default=0)),
                ('covers', models.PositiveIntegerField(default=0)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('digital_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('beer_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('spirits_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('wine_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('soft_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('food_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_snapshots_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-synced_at', '-id'],
                'indexes': [models.Index(fields=['business_date'], name='sales_sales_busines_de2e55_idx'), models.Index(fields=['source', 'business_date'], name='sales_sales_source_473acf_idx'), models.Index(fields=['location_name', 'business_date'], name='sales_sales_locatio_fbffa5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='salessnapshot',
            constraint=models.UniqueConstraint(fields=('location_name', 'source', 'business_date'), name='uniq_sales_snapshot_location_source_date'),
        ),
    ]
