# Generated by Django 4.2.30 on 2026-07-07 14:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('TOAST', 'Toast'), ('LIGHTSPEED', 'Lightspeed'), ('SQUARE', 'Square'), ('CLOVER', 'Clover'), ('OTHER', 'Other')], default='TOAST', max_length=24)),
                ('account_identifier', models.CharField(blank=True, max_length=120)),
                ('api_base_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=80)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('is_enabled', models.BooleanField(default=True)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('webhook_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_integrations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='PosWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('external_event_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='RECEIVED', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='sales.posintegration')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['integration', 'received_at'], name='sales_poswe_integra_35c546_idx'), models.Index(fields=['status', 'received_at'], name='sales_poswe_status_7c89b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PosSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('WEBHOOK', 'Webhook')], default='MANUAL', max_length=16)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('locations_touched', models.PositiveIntegerField(default=0)),
                ('snapshots_imported', models.PositiveIntegerField(default=0)),
                ('imported_net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payload_summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='sales.posintegration')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sync_runs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='sales_possy_status_90740f_idx'), models.Index(fields=['integration', 'started_at'], name='sales_possy_integra_6f0705_idx')],
            },
        ),
        migrations.CreateModel(
            name='PosLocationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_location_id', models.CharField(max_length=120)),
                ('external_location_name', models.CharField(max_length=120)),
                ('internal_location_name', models.CharField(max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_import_enabled', models.BooleanField(default=True)),
                ('latest_business_date', models.DateField(blank=True, null=True)),
                ('latest_net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_mappings', to='sales.posintegration')),
            ],
            options={
                'ordering': ['integration__label', '-is_primary', 'internal_location_name'],
                'indexes': [models.Index(fields=['internal_location_name'], name='sales_poslo_interna_438928_idx'), models.Index(fields=['is_active', 'auto_import_enabled'], name='sales_poslo_is_acti_e8e80c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='poslocationmapping',
            constraint=models.UniqueConstraint(fields=('integration', 'external_location_id'), name='uniq_pos_mapping_external_location'),
        ),
        migrations.AddIndex(
            model_name='posintegration',
            index=models.Index(fields=['provider', 'is_enabled'], name='sales_posin_provide_1f3c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='posintegration',
            index=models.Index(fields=['last_success_at'], name='sales_posin_last_su_fe49d6_idx'),
        ),
    ]
