# Generated by Django 4.2.30 on 2026-07-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation_venue_venueinvite_venuemembership_and_more'),
        ('sales', '0002_posintegration_poswebhookevent_possyncrun_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salessnapshot',
            name='uniq_sales_snapshot_location_source_date',
        ),
        migrations.AddField(
            model_name='posintegration',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_integrations', to='accounts.venue'),
        ),
        migrations.AddField(
            model_name='salessnapshot',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_snapshots', to='accounts.venue'),
        ),
        migrations.AddIndex(
            model_name='posintegration',
            index=models.Index(fields=['venue', 'provider', 'is_enabled'], name='sales_posin_venue_i_f1c966_idx'),
        ),
        migrations.AddIndex(
            model_name='salessnapshot',
            index=models.Index(fields=['venue', 'business_date'], name='sales_sales_venue_i_fdae08_idx'),
        ),
        migrations.AddConstraint(
            model_name='salessnapshot',
            constraint=models.UniqueConstraint(fields=('venue', 'location_name', 'source', 'business_date'), name='uniq_sales_snapshot_venue_location_source_date'),
        ),
    ]
