# Generated by Django 4.2.30 on 2026-07-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_staffprofile_notify_on_shift_assignment_and_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('default_shift_start_time', models.TimeField(blank=True, null=True)),
                ('default_shift_end_time', models.TimeField(blank=True, null=True)),
                ('low_stock_buffer_percent', models.PositiveSmallIntegerField(default=50)),
                ('dashboard_focus', models.CharField(choices=[('OPERATIONS', 'Operations'), ('TRADE', 'Trade'), ('SERVICE', 'Service')], default='OPERATIONS', max_length=16)),
                ('opening_handover_prompt', models.TextField(blank=True)),
                ('closing_handover_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='accounts.organisation')),
            ],
            options={
                'ordering': ['organisation__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('LANDLORD', 'Landlord'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('token', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_shift_assignment', models.BooleanField(default=True)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_venue_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LANDLORD', 'Landlord'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notify_on_shift_assignment', models.BooleanField(default=True)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_memberships_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_memberships', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.venue')),
            ],
            options={
                'ordering': ['venue__name', 'user__username'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_ve_user_id_a5fb76_idx'), models.Index(fields=['venue', 'role', 'is_active'], name='accounts_ve_venue_i_e8d9c7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='venuemembership',
            constraint=models.UniqueConstraint(fields=('venue', 'user'), name='uniq_venue_membership_user'),
        ),
        migrations.AddIndex(
            model_name='venueinvite',
            index=models.Index(fields=['venue', 'is_active'], name='accounts_ve_venue_i_0dcd80_idx'),
        ),
        migrations.AddIndex(
            model_name='venueinvite',
            index=models.Index(fields=['email', 'is_active'], name='accounts_ve_email_9c8725_idx'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('organisation', 'slug'), name='uniq_venue_org_slug'),
        ),
    ]
