# Generated by Django 4.2.30 on 2026-07-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_organisation_venue_venueinvite_venuemembership_and_more'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='handover_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='handover_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_handovers_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='handover_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.venue'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['venue', 'shift_date'], name='shifts_shif_venue_i_0eff7a_idx'),
        ),
    ]
