# Generated by Django 4.2.30 on 2026-04-22 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('checklist_type', models.CharField(choices=[('OPENING', 'Opening'), ('CLOSING', 'Closing'), ('DELIVERY', 'Delivery'), ('CLEANING', 'Cleaning')], max_length=20)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'due_date', 'created_at'],
                'indexes': [models.Index(fields=['checklist_type'], name='checklists__checkli_a8f102_idx'), models.Index(fields=['completed'], name='checklists__complet_8a6ac2_idx'), models.Index(fields=['due_date'], name='checklists__due_dat_8baf97_idx')],
            },
        ),
    ]
