# Generated by Django 4.2.30 on 2026-07-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_organisation_venue_venueinvite_venuemembership_and_more'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('checklist_type', models.CharField(choices=[('OPENING', 'Opening'), ('CLOSING', 'Closing'), ('DELIVERY', 'Delivery'), ('CLEANING', 'Cleaning')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['checklist_type', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DailySignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signoff_type', models.CharField(choices=[('OPENING', 'Opening'), ('CLOSING', 'Closing')], max_length=16)),
                ('business_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-business_date', 'signoff_type'],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='accounts.venue'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['venue', 'checklist_type'], name='checklists__venue_i_a13f33_idx'),
        ),
        migrations.AddField(
            model_name='dailysignoff',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_signoffs_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysignoff',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_signoffs', to='accounts.venue'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='accounts.venue'),
        ),
        migrations.AddIndex(
            model_name='dailysignoff',
            index=models.Index(fields=['venue', 'business_date'], name='checklists__venue_i_4e147d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailysignoff',
            constraint=models.UniqueConstraint(fields=('venue', 'signoff_type', 'business_date'), name='uniq_daily_signoff_per_venue_day'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['venue', 'checklist_type', 'is_active'], name='checklists__venue_i_1bb39e_idx'),
        ),
    ]
