# Generated by Django 4.2.30 on 2026-04-22 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('BEER_BARRELS', 'Beer Barrels'), ('SPIRITS', 'Spirits'), ('WINE', 'Wine'), ('SOFT_DRINKS', 'Soft Drinks'), ('MIXERS', 'Mixers'), ('GLASSWARE', 'Glassware'), ('CLEANING', 'Cleaning Supplies'), ('GARNISHES', 'Garnishes'), ('SNACKS', 'Snacks')], max_length=40)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('BARRELS', 'Barrels'), ('BOTTLES', 'Bottles'), ('CANS', 'Cans'), ('BOXES', 'Boxes'), ('LITRES', 'Litres'), ('KG', 'Kg'), ('UNITS', 'Units')], default='UNITS', max_length=20)),
                ('minimum_level', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='stock_stock_categor_1d8790_idx'), models.Index(fields=['is_active'], name='stock_stock_is_acti_8c64b7_idx')],
            },
        ),
    ]
