# Generated by Django 4.2.30 on 2026-07-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation_venue_venueinvite_venuemembership_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='last_counted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='accounts.venue'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['venue', 'category'], name='stock_stock_venue_i_09a0ea_idx'),
        ),
    ]
