# Generated by Django 4.2.30 on 2026-04-22 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('issue_type', models.CharField(choices=[('BROKEN', 'Broken'), ('MISSING', 'Missing'), ('DAMAGED', 'Damaged'), ('REPLACEMENT_NEEDED', 'Replacement Needed')], max_length=22)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakages_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_type'], name='breakages_b_issue_t_a77015_idx'), models.Index(fields=['created_at'], name='breakages_b_created_42fc48_idx')],
            },
        ),
    ]
