# Generated by Django 4.2.30 on 2026-07-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_organisation_venue_venueinvite_venuemembership_and_more'),
        ('breakages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakage',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breakage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakages_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakage',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FOLLOW_UP', 'Needs Follow-up'), ('CLOSED', 'Closed')], default='OPEN', max_length=16),
        ),
        migrations.AddField(
            model_name='breakage',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakages', to='accounts.venue'),
        ),
        migrations.AddIndex(
            model_name='breakage',
            index=models.Index(fields=['venue', 'status', 'created_at'], name='breakages_b_venue_i_541e31_idx'),
        ),
    ]
