# Generated by Django 4.2.30 on 2026-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category_supplied', models.CharField(choices=[('BEER_BARRELS', 'Beer Barrels'), ('SPIRITS', 'Spirits'), ('WINE', 'Wine'), ('SOFT_DRINKS', 'Soft Drinks'), ('MIXERS', 'Mixers'), ('GLASSWARE', 'Glassware'), ('CLEANING', 'Cleaning Supplies'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
