# Generated by Django 4.2.30 on 2026-04-24 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('STATUS', 'Status Update'), ('TOGGLE', 'Toggle'), ('SETTINGS', 'Settings')], max_length=16)),
                ('target_model', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['target_model', 'created_at'], name='audit_audit_target__49986f_idx'), models.Index(fields=['actor_username', 'created_at'], name='audit_audit_actor_u_058125_idx')],
            },
        ),
    ]
