# Generated by Django 4.2.30 on 2026-07-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation_venue_venueinvite_venuemembership_and_more'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.venue'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['venue', 'created_at'], name='audit_audit_venue_i_c1aaf8_idx'),
        ),
    ]
